/* RELIC ROUTE — one renderer for the interactive prototype and the film. */
(() => {
  'use strict';
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const W=1600,H=900, C={ink:'#102321',paper:'#f0edde',white:'#fbf8ed',acid:'#e1ef9c',muted:'#a7b3a7',line:'#55655a',copper:'#bd8f63',rust:'#d09873'};
  const tasks=[
    {id:'01',name:'落锚船坞',en:'THE ANCHOR DOCK',code:'D-03',risk:'低',time:'12',reward:'封存铭牌',desc:'在失重货舱中，回收仍保留编号的陶瓷铭牌。',warning:'船体稳定，注意漂浮的陶瓷碎片。',object:'缺角的陶瓷铭牌。编号刻痕仍然清晰，像一封尚未送出的信。',coords:'24° 18′ / 07° 36′',x:600,y:665},
    {id:'02',name:'静默环站',en:'THE SILENT OBSERVATORY',code:'M-07',risk:'中',time:'24',reward:'同心环光核',desc:'从废弃观测环的核心舱中，取回持续发光的同心环核。',warning:'核心舱仍有周期脉冲，回收窗口有限。',object:'观测环的低温光源。外壳保留修补痕迹，核心仍在规律地呼吸。',coords:'36° 42′ / 11° 09′',x:974,y:429},
    {id:'03',name:'铜蚀残带',en:'THE VERDIGRIS BELT',code:'V-12',risk:'高',time:'38',reward:'刻纹铜环',desc:'穿过缓慢漂移的碎片，寻找带有观测刻纹的外环。',warning:'碎片轨迹交错，航线需随时校正。',object:'残缺的铜质外环。锈蚀之下，一段完整的星图刻纹被保留下来。',coords:'48° 03′ / 15° 22′',x:1106,y:691}
  ];
  const state={screen:'map',selected:1,revealed:false,claimed:false,hover:'',pressed:'',transition:null,selectionAt:0,scanAt:0,film:false,filmPaused:false,filmAt:0,filmStart:0,reduced:matchMedia('(prefers-reduced-motion:reduce)').matches,sound:false,ready:false,recording:false};
  const art={field:new Image(),core:new Image()}; art.field.src='assets/field.png';art.core.src='assets/lumen-core.png';
  let audio=null,now=0,lastRender=-1;
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),ease=t=>1-Math.pow(1-clamp(t),3);
  const font=(size,weight=400,family='Archive')=>`${weight} ${size}px ${family}, "PingFang SC", sans-serif`;
  function text(s,x,y,size=18,color=C.paper,weight=400,align='left',family='Archive') {ctx.fillStyle=color;ctx.font=font(size,weight,family);ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.fillText(s,x,y);}
  function tracked(s,x,y,size=13,color=C.muted,space=2){ctx.font=font(size,500);ctx.fillStyle=color;ctx.textAlign='left';for(const ch of s){ctx.fillText(ch,x,y);x+=ctx.measureText(ch).width+space;}}
  function wrap(s,x,y,width,size=18,color=C.muted,lineHeight=31){ctx.font=font(size);let line='',row=0;for(const ch of s){if(ctx.measureText(line+ch).width>width){text(line,x,y+row*lineHeight,size,color);line=ch;row++;}else line+=ch;}if(line)text(line,x,y+row*lineHeight,size,color);}
  function rect(x,y,w,h,fill,stroke=null){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,w-1,h-1);}}
  function line(x,y,x2,y2,color=C.line,width=1){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
  function circle(x,y,r,color,stroke=null,width=1){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(color){ctx.fillStyle=color;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
  function arrow(x,y,color=C.ink,left=false){const d=left?-1:1;line(x-10*d,y,x+10*d,y,color,2);line(x+10*d,y,x+3*d,y-7,color,2);line(x+10*d,y,x+3*d,y+7,color,2);}
  function diamond(x,y,r=5,color=C.acid){ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.closePath();ctx.fillStyle=color;ctx.fill();}
  function mark(x,y,s=1,color=C.paper){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,17,.35,Math.PI*1.62);ctx.stroke();ctx.beginPath();ctx.arc(0,0,8,Math.PI+.35,Math.PI*2+.3);ctx.stroke();line(-19,19,19,-19,color,2);diamond(15,-15,4,color);ctx.restore();}
  function tag(label,x,y,fill=C.acid,color=C.ink){ctx.font=font(12,500);const w=ctx.measureText(label).width+22;rect(x,y,w,25,fill);text(label,x+11,y+18,12,color,500);return w;}
  function button(id,label,x,y,w,h=64,primary=true,disabled=false){const active=state.hover===id,pressed=state.pressed===id;const bg=disabled?'#35483e':primary?(pressed?'#bbcd7f':active?'#f0f5c9':C.acid):active?'#33483d':'#182a24';rect(x,y,w,h,bg,primary?null:'#657666');text(label,x+24,y+h/2+7,19,disabled?C.muted:primary?C.ink:C.paper,600);arrow(x+w-32,y+h/2,disabled?C.muted:primary?C.ink:C.acid);if(pressed)rect(x,y+h-3,w,3,C.white);}
  function backButton(label='返回星图'){arrow(80,140,C.paper,true);text(label,103,146,15,C.paper,500);}
  function cover(img,x,y,w,h){if(!img.complete||!img.naturalWidth)return;const scale=Math.max(w/img.width,h/img.height),iw=img.width*scale,ih=img.height*scale;ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih);}
  function background(dim=.15){rect(0,0,W,H,'#10201b');cover(art.field,0,0,W,H);let g=ctx.createLinearGradient(0,0,W,0);g.addColorStop(0,'rgba(6,18,16,.93)');g.addColorStop(.3,'rgba(6,18,16,.66)');g.addColorStop(.62,`rgba(6,18,16,${dim})`);g.addColorStop(1,'rgba(6,18,16,.65)');rect(0,0,W,H,g);g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'rgba(8,20,17,.68)');g.addColorStop(.28,'rgba(8,20,17,0)');g.addColorStop(.78,'rgba(8,20,17,.08)');g.addColorStop(1,'rgba(8,20,17,.93)');rect(0,0,W,H,g);}
  function header(step='01 / 导航'){mark(83,59,.85);text('RELIC ROUTE',116,70,31,C.paper,900,'left','Route');text('异物航线',316,66,18,C.paper,500);line(420,48,420,73,'#66786b');tracked('DEEP SPACE ARCHAEOLOGY',447,65,12);text('打捞行动',1225,65,16,C.paper,500);text('远航局 / 第七观测区',1536,65,14,C.muted,400,'right');line(64,102,1536,102,'#526051');tracked(step,64,848,13,C.muted);tracked('ARCHIVE  /  0341—09',1250,848,12,C.muted);}
  function grid(x=548,y=169,w=620,h=635){ctx.save();ctx.globalAlpha=.32;for(let gx=x;gx<x+w;gx+=76)line(gx,y,gx,y+h,'#5a6955',.5);for(let gy=y;gy<y+h;gy+=76)line(x,gy,x+w,gy,'#5a6955',.5);ctx.restore();}
  function bracket(x,y,r,color=C.acid){for(const [sx,sy] of [[-1,-1],[1,-1],[-1,1],[1,1]]){line(x+sx*r,y+sy*r,x+sx*(r-13),y+sy*r,color,1.5);line(x+sx*r,y+sy*r,x+sx*r,y+sy*(r-13),color,1.5);}}
  function relic(x,y,size,taskIndex=state.selected,alpha=1){ctx.save();ctx.globalAlpha*=alpha;if(taskIndex===1&&art.core.complete&&art.core.naturalWidth){ctx.drawImage(art.core,x-size/2,y-size/2,size,size);}else if(taskIndex===0){ctx.translate(x,y);ctx.rotate(-.18);ctx.shadowColor='rgba(0,0,0,.2)';ctx.shadowBlur=20;ctx.fillStyle=C.paper;ctx.beginPath();ctx.moveTo(-size*.3,-size*.23);ctx.lineTo(size*.22,-size*.23);ctx.lineTo(size*.3,-size*.14);ctx.lineTo(size*.3,size*.23);ctx.lineTo(-size*.3,size*.23);ctx.closePath();ctx.fill();ctx.shadowBlur=0;rect(-size*.23,-size*.17,size*.46,size*.34,'#dad4c0','#a09379');text('0341',-size*.15,size*.04,size*.1,'#53635a',500);line(-size*.16,size*.1,size*.16,size*.1,'#9c9072',2);for(const sx of [-1,1])circle(sx*size*.245,0,size*.022,C.copper);}else{ctx.translate(x,y);ctx.rotate(-.25);ctx.strokeStyle=C.copper;ctx.lineWidth=size*.14;ctx.beginPath();ctx.arc(0,0,size*.32,-.6,Math.PI*1.43);ctx.stroke();ctx.strokeStyle='#77917c';ctx.lineWidth=size*.037;ctx.beginPath();ctx.arc(0,0,size*.32,-.6,Math.PI*1.43);ctx.stroke();for(let i=0;i<18;i++){const a=i*.31-.5;line(Math.cos(a)*size*.265,Math.sin(a)*size*.265,Math.cos(a)*size*.36,Math.sin(a)*size*.36,'#d6bf95',1.5);}}ctx.restore();}
  function mapScreen(t){const task=tasks[state.selected];background(.13);grid();header();tracked('RECOVERY PROGRAMME  /  SECTOR VII',64,163,12);text('第七观测区',59,251,64,C.paper,650);text('异常信号',59,344,76,C.paper,650);text('选择回收目标，规划下一次出航。',66,386,17,C.muted);text('可用任务',64,440,16,C.paper,500);text('03',457,440,15,C.muted,400,'right');
    for(let i=0;i<3;i++){const a=tasks[i],y=463+i*105,sel=i===state.selected,hov=state.hover===`node-${i}`;rect(64,y,393,91,sel?C.acid:hov?'rgba(48,70,54,.95)':'rgba(14,29,24,.87)',sel?null:'#63715d');text(a.id,83,y+30,16,sel?'#4c6045':C.muted,600);text(a.name,122,y+36,24,sel?C.ink:C.paper,600);tracked(a.code+' / '+a.time+' MIN',122,y+67,11,sel?'#4c6045':C.muted,1);text('风险 '+a.risk,438,y+67,12,sel?C.ink:C.muted,400,'right');if(sel)arrow(427,y+28,C.ink);else circle(427,y+27,4,null,C.line);}
    const nodes=tasks;ctx.save();ctx.setLineDash([3,8]);line(nodes[0].x,nodes[0].y,nodes[1].x,nodes[1].y,'#b7c8a0');line(nodes[1].x,nodes[1].y,nodes[2].x,nodes[2].y,'#b7c8a0');ctx.restore();
    for(let i=0;i<3;i++){const a=nodes[i],sel=state.selected===i;circle(a.x,a.y,27,'rgba(14,29,24,.8)',sel?C.acid:'#8a9881');circle(a.x,a.y,4,sel?C.acid:C.paper);const lx=i===2?a.x-40:a.x+40,align=i===2?'right':'left';text(a.name,lx,a.y-6,18,C.paper,600,align);text(a.code,lx,a.y+21,12,C.muted,500,align);if(sel){bracket(a.x,a.y,39);const pulse=state.reduced?0:clamp((t-state.selectionAt)/220);for(let n=0;n<3;n++){const rr=60+n*29+(1-ease(pulse))*36;ctx.save();ctx.globalAlpha=.26;ctx.beginPath();ctx.ellipse(a.x,a.y,rr,rr*.64,-.35,.2,Math.PI*1.7);ctx.strokeStyle=C.acid;ctx.lineWidth=1;ctx.stroke();ctx.restore();}tag('已选中',a.x-31,a.y-81);}}
    rect(1202,291,334,445,'rgba(12,27,23,.9)','#798369');tracked('SELECTED SIGNAL',1226,326,11,C.acid);text(task.name,1226,371,30,C.paper,600);line(1226,395,1512,395,'#64725c');wrap(task.desc,1226,426,283,16,C.muted,29);text('信号坐标',1226,518,12,C.muted);text(task.coords,1226,546,16,C.paper);text('预估周期',1226,596,12,C.muted);text(task.time,1226,640,39,C.paper,500);text('分钟',1283,639,14,C.muted);tag('风险 / '+task.risk,1427,612,task.risk==='高'?'#c98c65':C.acid);button('details','查看任务',1226,660,286,54);tracked('FOCUS / '+task.code,576,795,12,C.acid);text('1—3 选择节点   /   Enter 查看任务',64,802,13,C.muted);
  }
  function dossierScreen(t){const task=tasks[state.selected];background(.42);header('02 / 任务档案');backButton();tracked('RECOVERY ORDER  /  '+task.code,64,209,12,C.acid);text(task.name,57,311,92,C.paper,600);tracked(task.en,66,354,17,C.muted,2.2);wrap(task.desc,66,418,784,24,C.paper,40);line(64,499,860,499,'#566851');text('01',64,544,16,C.acid,600);text('进入观测区',111,543,21,C.paper,500);text('在指定区域锁定遗物的回收信号。',111,577,16,C.muted);text('02',64,629,16,C.acid,600);text('完整封存',111,628,21,C.paper,500);text('保留遗物外壳与编号，交由远航局登记。',111,662,16,C.muted);button('confirm','核对航线',64,725,366);text('目标与奖励将在下一步再次确认。',458,764,14,C.muted);
    rect(1016,160,520,628,C.paper);tracked('RECOVERY TARGET  /  0'+(state.selected+1),1048,204,12,'#536454');text('回收目标',1048,245,27,C.ink,600);line(1048,270,1504,270,'#b6bba7');circle(1276,415,142,null,'#c1c4ac');circle(1276,415,120,null,'#ced0bd');relic(1276,415,278);bracket(1276,415,153,'#8a9b72');text(task.reward,1276,612,29,C.ink,600,'center');text('封存 / 编目 / 保留原始状态',1276,646,13,'#697a64',400,'center');rect(1048,677,456,80,'#d8debd');text('风险 '+task.risk+'  ·  预估 '+task.time+' 分钟',1065,706,14,C.ink,600);wrap(task.warning,1065,733,420,13,'#536454',22);
  }
  function confirmScreen(t){const task=tasks[state.selected];background(.5);rect(0,0,W,H,'rgba(9,22,17,.48)');header('03 / 航线确认');backButton('返回任务');
    const x=348,y=178,w=904;rect(x,y,w,592,C.paper);rect(x,y,10,592,C.acid);tracked('FLIGHT PLAN  /  FINAL CHECK',x+45,y+48,12,'#536454');text('即将前往',x+45,y+102,28,C.ink,500);text(task.name,x+39,y+195,74,C.ink,650);tag('航线 '+task.code,x+w-174,y+42,'#d9dfbd');line(x+45,y+234,x+w-45,y+234,'#abb3a0');text('回收目标',x+45,y+278,14,'#667a60');text(task.reward,x+45,y+313,24,C.ink,600);text('风险等级',x+354,y+278,14,'#667a60');text(task.risk,x+354,y+313,24,C.ink,600);text('预估周期',x+645,y+278,14,'#667a60');text(task.time+' 分钟',x+645,y+313,24,C.ink,600);line(x+45,y+348,x+w-45,y+348,'#abb3a0');wrap(task.warning,x+45,y+393,w-90,18,'#536454',30);text('核对目标后，锁定本次航线。',x+45,y+437,16,'#536454');button('depart','确认航线',x+45,y+478,492,66);button('cancel','返回修改',x+559,y+478,300,66,false);text('准备就绪',x+45,y+574,12,'#536454');circle(x+113,y+570,3,'#78974f');text('远航局 / 第七观测区',x+w-45,y+574,12,'#536454',400,'right');
  }
  function rewardScreen(t,overrideScan=null){const task=tasks[state.selected];const scanning=state.scanAt>0&&!state.revealed;let progress=overrideScan!==null?overrideScan:scanning?clamp((t-state.scanAt)/900):state.revealed?1:0;
    background(.69);rect(0,0,W,H,'rgba(12,28,24,.61)');grid(488,161,640,616);header('04 / 回收登记');tag('任务完成',64,142);tracked('SALVAGE REPORT  /  '+task.code,64,211,12,C.muted);text(state.claimed?'归档完成。':'失落的光，',57,305,75,C.paper,600);text(state.claimed?'航线仍在继续。':'再次被看见。',57,397,state.claimed?55:61,C.paper,600);wrap(state.claimed?'已入库。本次回收已登记。':state.revealed?task.object:'封存完整，等待识别。',66,464,430,19,C.muted,34);
    text('遗物编号',66,600,12,C.muted);tracked('R—0341 / '+task.code,66,631,18,C.paper,1.5);text('来源区域',66,683,12,C.muted);text(task.name,66,718,21,C.paper,500);text('回收状态',66,770,12,C.muted);text(state.claimed?'已入库':state.revealed?'识别完成':scanning?'正在识别…':'等待识别',66,804,17,C.acid,500);
    const cx=910,cy=470;circle(cx,cy,275,null,'#708363');circle(cx,cy,248,null,'#344e3c');bracket(cx,cy,283,'#788b66');tracked('OBJECT SCAN',686,173,11,C.muted);text('RV / '+task.id,1111,173,12,C.muted,400,'right');
    if(progress===0){ctx.save();ctx.globalAlpha=.09;relic(cx,cy,440);ctx.restore();circle(cx,cy,136,'rgba(20,43,34,.9)','#c7d38c');for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(cx,cy,76+i*11,i*.7,i*.7+Math.PI*1.3);ctx.strokeStyle=i%2?C.acid:'#667b4d';ctx.lineWidth=i===0?2:1;ctx.stroke();}mark(cx,cy,1.7,C.acid);text('封存中',cx,cy+192,15,C.muted,400,'center');}
    else if(progress<1){ctx.save();ctx.beginPath();for(let row=-6;row<=6;row++)for(let col=-6;col<=6;col++){const threshold=Math.hypot(row,col)*.054+(Math.sin(row*1.83+col*2.71)+1)*.08,local=clamp((progress-threshold)*5),r=local*34;if(r>0){ctx.moveTo(cx+col*40+r,cy+row*40);ctx.arc(cx+col*40,cy+row*40,r,0,Math.PI*2);}}ctx.clip();relic(cx,cy,488);ctx.restore();const sy=cy-245+490*progress;line(cx-245,sy,cx+245,sy,C.acid,2);ctx.save();ctx.globalAlpha=.44;for(let i=0;i<60;i++){const xx=cx-238+(i*73%476),yy=sy-50+(i*29%100),rr=2+Math.sin(i*1.9+progress*12)*1.6;circle(xx,yy,rr,C.acid);}ctx.restore();text('正在识别遗物…',cx,cy+322,14,C.acid,400,'center');}
    else{relic(cx,cy,488);circle(cx,cy,264,null,'#91a56a');tag('识别完成',cx-38,cy+284);}
    rect(1242,297,294,425,'rgba(18,39,30,.94)','#768765');tracked(state.claimed?'ARCHIVED':'RECOVERED OBJECT',1266,335,11,C.acid);text(state.revealed?task.reward:'未知遗物',1266,386,27,C.paper,600);line(1266,412,1512,412,'#5d7256');text('保存等级',1266,454,13,C.muted);text('完整封存',1266,488,21,C.paper,500);text('所属档案',1266,543,13,C.muted);text('第七观测区',1266,575,18,C.paper);if(state.claimed){button('back-map','返回星图',1266,644,246,54);tag('已入库 ✓',1266,604,'#4a6545',C.acid);}else if(state.revealed)button('claim','领取遗物',1266,644,246,54);else button('scan',scanning?'识别中…':'识别遗物',1266,644,246,54,true,scanning);text('返回星图',1316,768,15,C.muted);arrow(1284,761,C.muted,true);
  }
  function closing(t){background(.65);rect(0,0,W,H,'rgba(7,20,15,.56)');mark(800,284,2.5,C.acid);text('RELIC ROUTE',800,438,114,C.paper,900,'center','Route');text('异 物 航 线',800,503,34,C.paper,500,'center');line(664,551,936,551,'#738762');tracked('向未知，取回光。',685,598,18,C.muted,3);text('GAME UI & MOTION DESIGN',800,793,14,C.muted,500,'center');}
  function paint(screen,t){if(screen==='map')mapScreen(t);else if(screen==='dossier')dossierScreen(t);else if(screen==='confirm')confirmScreen(t);else if(screen==='reward')rewardScreen(t);else closing(t);}
  function transitionPaint(tr,t){const p=clamp((t-tr.at)/tr.duration),e=ease(p),fold=(tr.from==='map'&&tr.to==='dossier')||(tr.from==='dossier'&&tr.to==='map');paint(tr.from,t);ctx.save();ctx.globalAlpha=e;paint(tr.to,t);ctx.restore();if(fold){const task=tasks[state.selected],f=tr.to==='dossier'?e:1-e,x=task.x+(1276-task.x)*f,y=task.y+(474-task.y)*f,w=14+506*f,h=14+614*f;ctx.save();ctx.globalAlpha=Math.sin(p*Math.PI);ctx.translate(x,y);ctx.transform(1,.12*(1-f),-.18*(1-f),1,0,0);rect(-w/2,-h/2,w,h,C.paper);line(-w*.38,-h*.26,w*.38,-h*.26,'#a8b397');if(w>150){line(-w*.38,-h*.15,w*.12,-h*.15,'#bac4a9',2);circle(0,h*.08,w*.24,null,'#c3cbb7');}ctx.restore();}else if(tr.to==='confirm'){ctx.save();ctx.globalAlpha=(1-e)*.42;rect(348+(1-e)*30,178+(1-e)*16,904-(1-e)*60,592-(1-e)*32,C.paper);ctx.restore();}}
  function render(t){now=t;if(!state.ready)return;if(state.film){if(!state.filmPaused)state.filmAt=clamp((t-state.filmStart)/1000,0,30);setFilmFrame(state.filmAt);if(state.filmAt>=30&&!state.recording){state.filmPaused=true;document.querySelector('#pause-film').textContent='重播';}}else if(state.scanAt&&!state.revealed&&t-state.scanAt>=900){state.revealed=true;state.scanAt=0;updateControls();announce('识别完成：'+tasks[state.selected].reward);}const tr=state.transition;if(tr&&t-tr.at<tr.duration&&!state.reduced){transitionPaint(tr,t);}else{if(tr)state.transition=null;paint(state.screen,t);}if(state.film){drawFilmIndicator();document.querySelector('#film-time').value=state.filmAt;document.querySelector('#film-time-label').value=timeLabel(state.filmAt)+' / 00:30';}if(state.pressed&&t-lastRender>150)state.pressed='';lastRender=t;}
  function loop(t){render(t);requestAnimationFrame(loop);}
  function announce(s){document.querySelector('#announcement').textContent=s;}
  function go(screen){const old=state.screen;state.screen=screen;state.transition={from:old,to:screen,at:performance.now(),duration:440};state.hover='';state.pressed='';updateControls();sound(screen==='reward'?'arrive':'open');}
  function act(id){if(state.film)return;if(id.startsWith('node-')){state.selected=+id.slice(5);state.selectionAt=performance.now();state.revealed=false;state.claimed=false;state.scanAt=0;updateControls(false);sound('select');announce('已选择 '+tasks[state.selected].name);}else if(id==='details')go('dossier');else if(id==='confirm')go('confirm');else if(id==='cancel')go('dossier');else if(id==='depart'){state.revealed=false;state.claimed=false;state.scanAt=0;go('reward');announce('航线已确认，进入演示结算。');}else if(id==='scan'&&!state.scanAt){sound('scan');if(state.reduced){state.revealed=true;updateControls();announce('识别完成：'+tasks[state.selected].reward);}else{state.scanAt=performance.now();updateControls(false);announce('正在识别遗物。');}}else if(id==='claim'&&state.revealed&&!state.claimed){state.claimed=true;updateControls();sound('claim');announce('已入库。本次回收已登记。');}else if(id==='back-map')go('map');else if(id==='back-dossier')go('dossier');}
  function updateControls(moveFocus=true){const root=document.querySelector('#controls');const task=tasks[state.selected],items=[];const add=(id,label,x,y,w,h=64,disabled=false)=>items.push({id,label,x,y,w,h,disabled});
    if(state.screen==='map'){for(let i=0;i<3;i++){add(`node-${i}`,`选择${tasks[i].name}：${tasks[i].risk}风险，${tasks[i].time}分钟`,64,463+i*105,393,91);add(`node-${i}-point`,`星图节点 ${tasks[i].name}`,tasks[i].x-28,tasks[i].y-28,56,56);}add('details','查看任务',1226,660,286,54);}
    else if(state.screen==='dossier'){add('back-map','返回星图',64,116,158,53);add('confirm','核对航线',64,725,366);}
    else if(state.screen==='confirm'){add('back-dossier','返回任务',64,116,158,53);add('depart','确认航线',393,656,492,66);add('cancel','返回修改',907,656,300,66);}
    else if(state.screen==='reward'){if(state.claimed)add('back-map','返回星图',1266,644,246,54);else if(state.revealed)add('claim','领取遗物',1266,644,246,54);else add('scan',state.scanAt?'正在识别遗物':'识别遗物',1266,644,246,54,!!state.scanAt);if(!state.claimed)add('back-map','返回星图',1266,741,180,54);}
    root.replaceChildren();if(!state.film)for(const item of items){const b=document.createElement('button');b.className='game-button';b.textContent=item.label;b.title=item.label;b.dataset.action=item.id;b.disabled=item.disabled;Object.assign(b.style,{left:item.x/W*100+'%',top:item.y/H*100+'%',width:item.w/W*100+'%',height:item.h/H*100+'%'});if(item.id.startsWith('node-'))b.setAttribute('aria-pressed',String(+item.id.split('-')[1]===state.selected));b.addEventListener('pointerenter',()=>state.hover=item.id.replace('-point',''));b.addEventListener('pointerleave',()=>{state.hover='';state.pressed='';});b.addEventListener('pointerdown',()=>state.pressed=item.id);b.addEventListener('pointerup',()=>state.pressed='');b.addEventListener('focus',()=>state.hover=item.id.replace('-point',''));b.addEventListener('blur',()=>state.hover='');b.addEventListener('click',()=>act(item.id.replace('-point','')));root.append(b);}
    const names={map:'任务星图',dossier:'任务详情',confirm:'出发确认',reward:'回收与奖励登记'};document.querySelector('#screen-title').textContent=names[state.screen]||'异物航线';document.querySelector('#screen-description').textContent=`${task.name}。${task.desc} 风险${task.risk}，预估${task.time}分钟。奖励：${task.reward}。${state.screen==='reward'?(state.claimed?'已入库。':state.revealed?'已识别，可领取。':state.scanAt?'正在识别遗物。':'等待识别。'):''}`;
    if(moveFocus&&!state.film)root.querySelector('.game-button:not(:disabled)')?.focus({preventScroll:true});
  }
  function sound(type){if(!state.sound)return;audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const presets={select:[440,660,.08],open:[220,440,.14],arrive:[110,330,.24],scan:[330,880,.3],claim:[660,990,.2]};const [a,b,d]=presets[type]||presets.select;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(a,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(b,audio.currentTime+d);gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+d);}
  function timeLabel(t){return '00:'+String(Math.floor(t)).padStart(2,'0');}
  function setFilmFrame(s){state.hover='';state.pressed='';for(const [cue,id] of [[5,'details'],[10,'confirm'],[14,'depart'],[17,'scan'],[23,'claim']]){if(s>=cue-.38&&s<cue)state.hover=id;if(s>=cue-.1&&s<cue)state.pressed=id;}state.selected=s<2?0:1;state.claimed=s>=23;state.revealed=s>=17.9;state.scanAt=s>=17&&s<17.9?now-(s-17)*1000:0;const screens=[['map',0],['dossier',5],['confirm',10],['reward',14],['closing',27]];let index=0;for(let i=0;i<screens.length;i++)if(s>=screens[i][1])index=i;state.screen=screens[index][0];state.selectionAt=s>=2?now-(s-2)*1000:now-250;const elapsed=s-screens[index][1];state.transition=null;if(index&&elapsed<.44&&!state.reduced)state.transition={from:screens[index-1][0],to:state.screen,at:now-elapsed*1000,duration:440};}
  function drawFilmIndicator(){if(state.screen==='closing')return;const labels={map:'01  /  聚焦 · 任务选择',dossier:'02  /  展开 · 读取任务',confirm:'03  /  确认 · 锁定航线',reward:state.claimed?'04  /  入库 · 完成反馈':state.revealed?'04  /  揭示 · 遗物识别':'04  /  封存 · 回收登记'};rect(548,838,567,36,'rgba(10,25,20,.88)');text(labels[state.screen],573,862,14,C.acid,500);}
  function startFilm(){state.hover='';state.pressed='';state.film=true;state.filmPaused=false;state.filmAt=0;state.filmStart=performance.now();state.transition=null;document.querySelector('#film-controls').hidden=false;document.querySelector('#pause-film').textContent='暂停';document.querySelector('#controls').replaceChildren();}
  function stopFilm(){state.film=false;state.filmPaused=false;state.scanAt=0;state.screen='map';state.selected=1;state.revealed=false;state.claimed=false;state.transition=null;document.querySelector('#film-controls').hidden=true;updateControls();}
  document.querySelector('#film').addEventListener('click',startFilm);document.querySelector('#exit-film').addEventListener('click',stopFilm);document.querySelector('#pause-film').addEventListener('click',()=>{if(state.filmAt>=30){startFilm();return;}state.filmPaused=!state.filmPaused;if(!state.filmPaused)state.filmStart=performance.now()-state.filmAt*1000;document.querySelector('#pause-film').textContent=state.filmPaused?'继续':'暂停';});document.querySelector('#film-time').addEventListener('input',e=>{state.filmAt=+e.target.value;state.filmStart=performance.now()-state.filmAt*1000;state.filmPaused=true;document.querySelector('#pause-film').textContent='继续';render(performance.now());});
  document.querySelector('#motion').setAttribute('aria-pressed',String(state.reduced));document.querySelector('#motion').addEventListener('click',e=>{state.reduced=!state.reduced;e.currentTarget.setAttribute('aria-pressed',String(state.reduced));if(state.scanAt){state.revealed=true;state.scanAt=0;updateControls(false);}});document.querySelector('#sound').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent='声音：'+(state.sound?'开':'关');e.currentTarget.setAttribute('aria-pressed',String(state.sound));sound('select');});
  document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,summary')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='Escape'){e.preventDefault();if(state.film)stopFilm();else if(state.screen==='confirm')go('dossier');else if(state.screen!=='map')go('map');}else if(!state.film&&state.screen==='map'&&['1','2','3'].includes(e.key)){e.preventDefault();act('node-'+(+e.key-1));}else if(!state.film&&e.key==='Enter'&&e.target===document.body){act({map:'details',dossier:'confirm',confirm:'depart',reward:state.claimed?'back-map':state.revealed?'claim':'scan'}[state.screen]);}});
  async function save(blob,name){const response=await fetch('/__export/'+name,{method:'POST',headers:{'Content-Type':blob.type},body:blob});if(!response.ok)throw Error('请用 scripts/serve.py 启动项目的本地导出服务。');return response.json();}
  const png=()=>new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
  document.querySelector('#export-frames').addEventListener('click',async()=>{const out=document.querySelector('#export-status');try{stopFilm();state.selected=1;state.transition=null;for(const [screen,name] of [['map','01-map.png'],['dossier','02-dossier.png'],['confirm','03-confirm.png'],['reward','04-reward.png']]){state.screen=screen;state.revealed=screen==='reward';state.claimed=false;state.scanAt=0;state.transition=null;state.hover='';state.pressed='';paint(screen,performance.now());await save(await png(),name);}state.screen='map';state.revealed=false;updateControls(false);out.textContent='四张 1600 × 900 原生界面图已保存到 showcase/。';}catch(error){out.textContent=error.message;}});
  document.querySelector('#export-film').addEventListener('click',async e=>{const exportButton=e.currentTarget,out=document.querySelector('#export-status');if(!window.MediaRecorder||!canvas.captureStream){out.textContent='此浏览器未提供 Canvas 视频录制能力。';return;}const type=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(v=>MediaRecorder.isTypeSupported(v));if(!type){out.textContent='此浏览器不支持 WebM；可观看演出或使用屏幕录制。';return;}exportButton.disabled=true;const chunks=[],stream=canvas.captureStream(60),recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:10000000});state.recording=true;startFilm();recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=async()=>{stream.getTracks().forEach(track=>track.stop());state.recording=false;state.filmPaused=true;try{await save(new Blob(chunks,{type}),'film.webm');out.textContent='30 秒原型演出已保存。可运行 scripts/encode-film.sh 生成带声音的 MP4。';}catch(error){out.textContent=error.message;}exportButton.disabled=false;};recorder.start(1000);out.textContent='录制中：0 / 30 秒';const tick=setInterval(()=>{out.textContent=`录制中：${Math.min(30,Math.floor(state.filmAt))} / 30 秒`;if(state.filmAt>=30){clearInterval(tick);recorder.stop();}},250);});
  if(new URLSearchParams(location.search).has('studio'))document.querySelector('#studio').hidden=false;
  Promise.all([document.fonts.load('400 18px Archive'),document.fonts.load('900 48px Route'),...Object.values(art).map(img=>img.decode())]).then(()=>{state.ready=true;document.querySelector('#loading').hidden=true;updateControls(false);if(new URLSearchParams(location.search).has('film'))startFilm();requestAnimationFrame(loop);}).catch(error=>{document.querySelector('#loading p').textContent='素材未能载入，请检查本地文件或刷新。';console.error(error);});
})();
